//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShips.Resources.Сonversations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameConverstations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameConverstations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShips.Resources.Сonversations.GameConverstations", typeof(GameConverstations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flee before I lose all sense of control.
        /// </summary>
        internal static string ComputerBattleship {
            get {
                return ResourceManager.GetString("ComputerBattleship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you still think to win?.
        /// </summary>
        internal static string ComputerCruiser {
            get {
                return ResourceManager.GetString("ComputerCruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender! You can&apos;t win this game!.
        /// </summary>
        internal static string ComputerDestroyer {
            get {
                return ResourceManager.GetString("ComputerDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got rid of splinters....
        /// </summary>
        internal static string ComputerTorpedoboat {
            get {
                return ResourceManager.GetString("ComputerTorpedoboat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see what i got!.
        /// </summary>
        internal static string DefaultMessage {
            get {
                return ResourceManager.GetString("DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck on my side.You can still surrender!.
        /// </summary>
        internal static string PlayerBattleship {
            get {
                return ResourceManager.GetString("PlayerBattleship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it really cruiser? Prepare to lose!.
        /// </summary>
        internal static string PlayerCruiser {
            get {
                return ResourceManager.GetString("PlayerCruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, nice! This is destroyer!.
        /// </summary>
        internal static string PlayerDestroyer {
            get {
                return ResourceManager.GetString("PlayerDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got your torpedo boat!.
        /// </summary>
        internal static string PlayerTorpedoboat {
            get {
                return ResourceManager.GetString("PlayerTorpedoboat", resourceCulture);
            }
        }
    }
}
