//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShips.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameDesignation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameDesignation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShips.Resources.GameDesignation", typeof(GameDesignation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        internal static string CursorBody {
            get {
                return ResourceManager.GetString("CursorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __.
        /// </summary>
        internal static string CursorFooter {
            get {
                return ResourceManager.GetString("CursorFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string EndLetter {
            get {
                return ResourceManager.GetString("EndLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,,.
        /// </summary>
        internal static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |  |.
        /// </summary>
        internal static string ShipBody {
            get {
                return ResourceManager.GetString("ShipBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |__|.
        /// </summary>
        internal static string ShipFooter {
            get {
                return ResourceManager.GetString("ShipFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __.
        /// </summary>
        internal static string ShipHeader {
            get {
                return ResourceManager.GetString("ShipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string StartLetter {
            get {
                return ResourceManager.GetString("StartLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     1  2  3  4  5  6  7  8  9 10
        ///   __ __ __ __ __ __ __ __ __ __
        /// |  |  |  |  |  |  |  |  |  |  |
        ///  |__|__|__|__|__|__|__|__|__|__|.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
