//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShips.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Serialization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Serialization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShips.Resources.Serialization", typeof(Serialization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string JsonExtention {
            get {
                return ResourceManager.GetString("JsonExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter path: ( Path be like: C:\\folder\\file.json(xml) ).
        /// </summary>
        internal static string LoadPath {
            get {
                return ResourceManager.GetString("LoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong. Try again. Press &quot;Esc&quot;.
        /// </summary>
        internal static string PathEx {
            get {
                return ResourceManager.GetString("PathEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter path: ( Path be like: C:\\folder\\file.json(xml) ).
        /// </summary>
        internal static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful conservation. Press &quot;Esc&quot;.
        /// </summary>
        internal static string SuccessfulSave {
            get {
                return ResourceManager.GetString("SuccessfulSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserPath {
            get {
                return ResourceManager.GetString("UserPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\Users\\.
        /// </summary>
        internal static string UsersFolderPath {
            get {
                return ResourceManager.GetString("UsersFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string XmlExtention {
            get {
                return ResourceManager.GetString("XmlExtention", resourceCulture);
            }
        }
    }
}
