//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShips.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShipConcrete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipConcrete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShips.Resources.ShipConcrete", typeof(ShipConcrete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BattleshipCount {
            get {
                return ResourceManager.GetString("BattleshipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string BattleshipDeck {
            get {
                return ResourceManager.GetString("BattleshipDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleship.
        /// </summary>
        internal static string BattleshipName {
            get {
                return ResourceManager.GetString("BattleshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CruiserCount {
            get {
                return ResourceManager.GetString("CruiserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CruiserDeck {
            get {
                return ResourceManager.GetString("CruiserDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruiser.
        /// </summary>
        internal static string CruiserName {
            get {
                return ResourceManager.GetString("CruiserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string DestroyerCount {
            get {
                return ResourceManager.GetString("DestroyerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DestroyerDeck {
            get {
                return ResourceManager.GetString("DestroyerDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer.
        /// </summary>
        internal static string DestroyerName {
            get {
                return ResourceManager.GetString("DestroyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string TorpedoBoatCount {
            get {
                return ResourceManager.GetString("TorpedoBoatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string TorpedoBoatDeck {
            get {
                return ResourceManager.GetString("TorpedoBoatDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedoboat.
        /// </summary>
        internal static string TorpedoBoatName {
            get {
                return ResourceManager.GetString("TorpedoBoatName", resourceCulture);
            }
        }
    }
}
